import type { Modalidade } from "./types";

/** Modalidades técnicas individuais (seção 8 do regulamento). */
export const MODALIDADES_TECNICAS: Modalidade[] = [
  {
    slug: "badminton",
    nome: "Badminton",
    tipo: "individual",
    familia: "sets",
    formato: "GP+SE",
    confederacao: "CBBd / BWF",
    categorias: ["jers-12-14", "jers-15-17"],
    naipes: ["Masculino", "Feminino", "Misto"],
    provas: [
      { slug: "simples-masc", nome: "Simples Masculino" },
      { slug: "simples-fem", nome: "Simples Feminino" },
      { slug: "duplas-masc", nome: "Duplas Masculino" },
      { slug: "duplas-fem", nome: "Duplas Feminino" },
      { slug: "duplas-mistas", nome: "Duplas Mistas" },
    ],
    limites_por_escola: {
      "jers-12-14": { masculino: 4, feminino: 4, minimo: null, observacao: "Simples + duplas + dupla mista" },
      "jers-15-17": { masculino: 4, feminino: 4, minimo: null, observacao: "Simples + duplas + dupla mista" },
    },
    pontuacao_grupos: { vitoria: 2, derrota: 1, wo: 0 },
    partida: {
      formato: "Melhor de 3 games (até 21 pts, vant. 2; limite 30×29)",
      tolerancia_inicio: "15 min",
    },
    desempates: [
      { ordem: 1, criterio: "Confronto direto" },
      { ordem: 2, criterio: "Quociente de games (vencidos ÷ perdidos)" },
      { ordem: 3, criterio: "Quociente de pontos (marcados ÷ sofridos)" },
      { ordem: 4, criterio: "Sorteio" },
    ],
    aliases: ["BADMINTON"],
  },
  {
    slug: "tenis-de-mesa",
    nome: "Tênis de Mesa",
    tipo: "individual",
    familia: "sets",
    formato: "GP+SE",
    confederacao: "CBTM / ITTF",
    categorias: ["tm-12-14", "tm-14-15", "tm-16-17"],
    naipes: ["Masculino", "Feminino"],
    provas: [
      { slug: "individual-masc", nome: "Individual Masculino" },
      { slug: "individual-fem", nome: "Individual Feminino" },
      { slug: "equipe-masc", nome: "Equipe Masculino" },
      { slug: "equipe-fem", nome: "Equipe Feminino" },
    ],
    limites_por_escola: {
      "tm-12-14": { masculino: 4, feminino: 4, minimo: null, observacao: "Individual + equipe" },
      "tm-14-15": { masculino: 4, feminino: 4, minimo: null, observacao: "Individual + equipe" },
      "tm-16-17": { masculino: 4, feminino: 4, minimo: null, observacao: "Individual + equipe" },
    },
    pontuacao_grupos: { vitoria: 2, derrota: 1, wo: 0 },
    partida: {
      individual: "Melhor de 5 games a 11 pts (vant. 2)",
      equipe: "Melhor de 5 games",
      grupos_classif: "Mín. 3, máx. 4 atletas",
      fase_ouro: "2 primeiros de cada grupo",
      fase_prata: "Demais atletas",
    },
    desempates: [
      { ordem: 1, criterio: "Confronto direto" },
      { ordem: 2, criterio: "Quociente de games" },
      { ordem: 3, criterio: "Quociente de pontos" },
      { ordem: 4, criterio: "Sorteio" },
    ],
    aliases: ["TENIS DE MESA", "TÊNIS DE MESA", "TM", "TABLE TENNIS", "PINGUE-PONGUE"],
  },
  {
    slug: "tiro-com-arco",
    nome: "Tiro com Arco",
    tipo: "individual",
    familia: "ranking",
    formato: "RANK",
    confederacao: "CBTARCO / World Archery",
    categorias: ["jers-12-14"],
    naipes: ["Masculino", "Feminino"],
    provas: [{ slug: "recurvo-individual", nome: "Arco Recurvo Individual" }],
    limites_por_escola: {
      "jers-12-14": { masculino: 4, feminino: 4, minimo: null, observacao: "Individual recurvo" },
    },
    partida: {
      round_indoor: "60 flechas a 18m, face 40cm full, 2 rounds de 10 séries de 3 flechas",
      tempo_serie: "1 min 30 seg",
      eliminatoria: "Set System: sets de 3 flechas; 2 pts por set vencido, 1 pt por empate",
      vitoria: "Primeiro a 6 pts de set · Shoot-off se empate 5×5",
    },
    desempates: [],
    aliases: ["TIRO COM ARCO", "TIRO ARCO", "ARCHERY"],
  },
  {
    slug: "xadrez",
    nome: "Xadrez",
    tipo: "individual",
    familia: "ranking",
    formato: "SUICO",
    confederacao: "CBX / FIDE",
    categorias: ["jers-12-14", "jers-15-17"],
    naipes: ["Masculino", "Feminino"],
    provas: [{ slug: "individual", nome: "Individual" }],
    limites_por_escola: {
      "jers-12-14": { masculino: 4, feminino: 4, minimo: null, observacao: "Coordenação pode autorizar adicionais" },
      "jers-15-17": { masculino: 4, feminino: 4, minimo: null, observacao: "Coordenação pode autorizar adicionais" },
    },
    pontuacao_grupos: { vitoria: 1, empate: 0.5, derrota: 0 },
    partida: {
      controle_tempo: "Rápido: 15 min + 10 seg/lance",
    },
    desempates: [
      { ordem: 1, criterio: "Buchholz (soma dos pontos dos adversários)" },
      { ordem: 2, criterio: "Buchholz cortado (menor resultado excluído)" },
      { ordem: 3, criterio: "Sonneborn-Berger" },
      { ordem: 4, criterio: "Número de vitórias" },
      { ordem: 5, criterio: "Confronto direto" },
      { ordem: 6, criterio: "Sorteio" },
    ],
    aliases: ["XADREZ", "CHESS"],
  },
  {
    slug: "ginastica-ritmica",
    nome: "Ginástica Rítmica",
    tipo: "individual",
    familia: "ranking",
    formato: "RANK",
    confederacao: "CBG / FIG",
    categorias: ["gr-12-13", "gr-14-15"],
    naipes: ["Feminino"],
    provas: [
      { slug: "arco", nome: "Arco" },
      { slug: "macas", nome: "Maças" },
    ],
    limites_por_escola: {
      "gr-12-13": { masculino: null, feminino: 4, minimo: null, observacao: "até 4 ginastas" },
      "gr-14-15": { masculino: null, feminino: 3, minimo: null, observacao: "até 3 ginastas" },
    },
    partida: {
      pontuacao: "Nota de Dificuldade (D) + Nota de Execução (E) − penalidades",
      classificacao: "Soma das notas dos aparelhos obrigatórios",
      ordem: "Sorteio",
    },
    desempates: [
      { ordem: 1, criterio: "Maior nota de Dificuldade acumulada" },
      { ordem: 2, criterio: "Maior nota de Execução acumulada" },
      { ordem: 3, criterio: "Menor penalidade acumulada" },
    ],
    aliases: ["GINASTICA RITMICA", "GINÁSTICA RÍTMICA", "GR"],
  },
];
