import type { Modalidade } from "./types";

/** Modalidades coletivas (seção 5 do regulamento). */
export const MODALIDADES_COLETIVAS: Modalidade[] = [
  {
    slug: "basquete",
    nome: "Basquetebol",
    tipo: "coletiva",
    familia: "score",
    formato: "GP+SE",
    confederacao: "CBB / FIBA",
    categorias: ["jers-12-14", "jers-15-17"],
    naipes: ["Masculino", "Feminino"],
    provas: [{ slug: "partida", nome: "Partida" }],
    limites_por_escola: {
      "jers-12-14": { masculino: 10, feminino: 10, minimo: 5 },
      "jers-15-17": { masculino: 10, feminino: 10, minimo: 5, observacao: "8 ou 10 atletas" },
    },
    pontuacao_grupos: { vitoria: 2, derrota: 1, wo: 0 },
    partida: {
      duracao: "4 × 10 min (tempo corrido interrompido)",
      prorrogacao: "5 min (quantas forem necessárias)",
      placar_wo: "20 × 0",
      bola_12_14: "Nº 6",
      bola_15_17_fem: "Nº 6",
      bola_15_17_masc: "Nº 7",
      altura_cesta: "3,05m",
    },
    desempates: [
      { ordem: 1, criterio: "Confronto direto entre os empatados" },
      { ordem: 2, criterio: "Quociente de pontos (marcados ÷ sofridos) nos jogos entre empatados" },
      { ordem: 3, criterio: "Quociente de pontos geral na fase" },
      { ordem: 4, criterio: "Maior número de pontos marcados" },
      { ordem: 5, criterio: "Sorteio" },
    ],
    aliases: ["BASQUETE", "BASQUETEBOL", "BASKET", "BASKETBALL"],
  },
  {
    slug: "futsal",
    nome: "Futsal",
    tipo: "coletiva",
    familia: "score",
    formato: "GP+SE",
    confederacao: "CBFS / FIFA",
    categorias: ["jers-12-14", "jers-15-17"],
    naipes: ["Masculino", "Feminino"],
    provas: [{ slug: "partida", nome: "Partida" }],
    limites_por_escola: {
      "jers-12-14": { masculino: 10, feminino: 10, minimo: 6, observacao: "Mirim" },
      "jers-15-17": { masculino: 10, feminino: 10, minimo: 6, observacao: "Infantil" },
    },
    pontuacao_grupos: { vitoria: 3, empate: 1, derrota: 0, wo: 0 },
    partida: {
      duracao_15_17: "2 × 20 min (tempo corrido)",
      duracao_12_14: "2 × 15 min (tempo corrido)",
      intervalo: "5 min",
      prorrogacao: "2 × 5 min",
      penaltis: "Série de 3 cobranças, depois alternadas",
      placar_wo: "3 × 0",
      bola_12_14: "Nº 3",
      bola_15_17: "Nº 4",
    },
    desempates: [
      { ordem: 1, criterio: "Confronto direto" },
      { ordem: 2, criterio: "Saldo de gols no confronto direto" },
      { ordem: 3, criterio: "Maior nº de gols marcados no confronto direto" },
      { ordem: 4, criterio: "Saldo de gols geral" },
      { ordem: 5, criterio: "Maior nº de gols marcados geral" },
      { ordem: 6, criterio: "Menor nº de cartões vermelhos" },
      { ordem: 7, criterio: "Menor nº de cartões amarelos" },
      { ordem: 8, criterio: "Sorteio" },
    ],
    aliases: ["FUTSAL", "FUTEBOL DE SALAO", "FUTEBOL DE SALÃO"],
  },
  {
    slug: "futebol",
    nome: "Futebol de Campo",
    tipo: "coletiva",
    familia: "score",
    formato: "GP+SE",
    confederacao: "CBF / FIFA",
    categorias: ["jers-15-17"],
    naipes: ["Masculino", "Feminino"],
    provas: [{ slug: "partida", nome: "Partida" }],
    limites_por_escola: {
      "jers-15-17": { masculino: 16, feminino: 16, minimo: 11 },
    },
    pontuacao_grupos: { vitoria: 3, empate: 1, derrota: 0, wo: 0 },
    partida: {
      duracao: "2 × 30 min (tempo corrido)",
      intervalo: "10 min",
      prorrogacao: "2 × 10 min",
      penaltis: "Série de 5 cobranças, depois alternadas",
      placar_wo: "3 × 0",
    },
    desempates: [
      { ordem: 1, criterio: "Confronto direto" },
      { ordem: 2, criterio: "Saldo de gols no confronto direto" },
      { ordem: 3, criterio: "Gols marcados no confronto direto" },
      { ordem: 4, criterio: "Saldo de gols geral" },
      { ordem: 5, criterio: "Gols marcados geral" },
      { ordem: 6, criterio: "Menor nº de cartões vermelhos" },
      { ordem: 7, criterio: "Menor nº de cartões amarelos" },
      { ordem: 8, criterio: "Sorteio" },
    ],
    aliases: ["FUTEBOL", "FUTEBOL DE CAMPO", "FOOTBALL", "SOCCER"],
  },
  {
    slug: "handebol",
    nome: "Handebol",
    tipo: "coletiva",
    familia: "score",
    formato: "GP+SE",
    confederacao: "CBHB / IHF",
    categorias: ["jers-12-14", "jers-15-17"],
    naipes: ["Masculino", "Feminino"],
    provas: [{ slug: "partida", nome: "Partida" }],
    limites_por_escola: {
      "jers-12-14": { masculino: 12, feminino: 12, minimo: 6 },
      "jers-15-17": { masculino: 14, feminino: 14, minimo: 6 },
    },
    pontuacao_grupos: { vitoria: 2, empate: 1, derrota: 0, wo: 0 },
    partida: {
      duracao: "2 × 25 min",
      prorrogacao: "2 × 5 min",
      penaltis: "Série de 5 cobranças",
      placar_wo: "5 × 0",
      todos_jogos_devem_ter_vencedor: true,
      bola_12_14: "H1",
      bola_15_17_fem: "H2",
      bola_15_17_masc: "H3",
    },
    desempates: [
      { ordem: 1, criterio: "Confronto direto" },
      { ordem: 2, criterio: "Saldo de gols no confronto direto" },
      { ordem: 3, criterio: "Gols marcados no confronto direto" },
      { ordem: 4, criterio: "Saldo de gols geral" },
      { ordem: 5, criterio: "Gols marcados geral" },
      { ordem: 6, criterio: "Sorteio" },
    ],
    aliases: ["HANDEBOL", "HANDBALL"],
  },
  {
    slug: "volei",
    nome: "Voleibol",
    tipo: "coletiva",
    familia: "sets",
    formato: "GP+SE",
    confederacao: "CBV / FIVB",
    categorias: ["jers-12-14", "jers-15-17"],
    naipes: ["Masculino", "Feminino"],
    provas: [{ slug: "partida", nome: "Partida" }],
    limites_por_escola: {
      "jers-12-14": { masculino: 12, feminino: 12, minimo: 6 },
      "jers-15-17": { masculino: 12, feminino: 12, minimo: 6 },
    },
    pontuacao_grupos: {
      "vitoria_3x0_3x1": 3, "derrota_0x3_1x3": 0,
      "vitoria_3x2": 2, "derrota_2x3": 1,
      "vitoria_2x0_classif": 2, "derrota_0x2_classif": 0,
      "vitoria_2x1_classif": 2, "derrota_1x2_classif": 1,
    },
    partida: {
      classificatoria: "Melhor de 2 sets (25 pts, vant. 2); tie-break: 1 set de 15 pts",
      final: "Melhor de 5 sets (25 pts sets 1–4, 15 pts set 5, vant. 2)",
      wo_classif: "2 × 0 (25×0 / 25×0)",
      wo_final: "3 × 0 (25×0 / 25×0 / 25×0)",
      menos_de_6_atletas: "Derrota por 2×0 (25×0 / 25×0) — não exclui da competição",
      altura_rede_12_14_fem: "2,10m",
      altura_rede_12_14_masc: "2,24m",
      altura_rede_15_17_fem: "2,24m",
      altura_rede_15_17_masc: "2,43m",
      distribuicao_24_equipes: "8 grupos × 3 equipes, 2 melhores de cada classificam",
      oitavas: "1ºA×2ºH, 1ºH×2ºA, 1ºB×2ºG, 1ºG×2ºB, 1ºC×2ºF, 1ºF×2ºC, 1ºD×2ºE, 1ºE×2ºD",
      quartas_semis: "MIT (Melhor Índice Técnico)",
    },
    desempates: [
      { ordem: 1, criterio: "Pontos na tabela" },
      { ordem: 2, criterio: "Quociente de sets (sets vencidos ÷ sets perdidos)" },
      { ordem: 3, criterio: "Quociente de pontos (pontos marcados ÷ pontos sofridos)" },
      { ordem: 4, criterio: "Confronto direto (repetir critérios 2 e 3 entre empatados)" },
      { ordem: 5, criterio: "Sorteio" },
    ],
    observacoes: ["Equipe que não perde nenhum set/ponto é classificada automaticamente pelo critério de average."],
    aliases: ["VOLEI", "VOLEIBOL", "VOLLEY", "VOLLEYBALL"],
  },
  {
    slug: "volei-de-praia",
    nome: "Vôlei de Praia",
    tipo: "coletiva",
    familia: "sets",
    formato: "RR",
    confederacao: "CBV / FIVB Beach",
    categorias: ["jers-12-14", "jers-15-17"],
    naipes: ["Masculino", "Feminino"],
    provas: [{ slug: "partida", nome: "Partida (dupla)" }],
    limites_por_escola: {
      "jers-12-14": { masculino: 4, feminino: 4, minimo: 2, observacao: "1 a 2 duplas" },
      "jers-15-17": { masculino: 4, feminino: 4, minimo: 2, observacao: "1 a 2 duplas; modalidade individual" },
    },
    pontuacao_grupos: { "vitoria_2x0": 3, "vitoria_2x1": 2, "derrota_1x2": 1, "derrota_0x2": 0 },
    partida: {
      formato: "Melhor de 3 sets",
      sets_1_2: "Até 21 pontos (vantagem de 2)",
      set_3: "Até 15 pontos (vantagem de 2)",
      altura_rede_12_14_fem: "2,20m",
      altura_rede_12_14_masc: "2,35m",
      altura_rede_15_17_fem: "2,24m",
      altura_rede_15_17_masc: "2,43m",
      regras_wo: [
        "Dupla presente impossibilitada por contusão: vencedora 2 pts, perdedora 1 pt; placar 2×0 (21×0/21×0)",
        "Dupla não comparece: vencedora 2 pts, perdedora 0 pts; placar 2×0 (21×0/21×0)",
        "Desistência durante partida: sets concluídos mantêm placar real; sets não disputados = 21×0",
      ],
    },
    desempates: [
      { ordem: 1, criterio: "Quociente de sets" },
      { ordem: 2, criterio: "Quociente de pontos" },
      { ordem: 3, criterio: "Sorteio" },
    ],
    aliases: ["VOLEI DE PRAIA", "VOLEIBOL DE PRAIA", "BEACH VOLLEY", "VÔLEI DE PRAIA"],
  },
];
