import type { Modalidade } from "./types";

/** Modalidades de tempo/marca (seção 7 do regulamento). */
export const MODALIDADES_TEMPO_MARCA: Modalidade[] = [
  {
    slug: "atletismo",
    nome: "Atletismo",
    tipo: "individual",
    familia: "time",
    formato: "RANK",
    confederacao: "CBAt",
    categorias: ["jers-12-14", "jers-15-17"],
    naipes: ["Masculino", "Feminino"],
    provas: [
      { slug: "75m", nome: "75m rasos" },
      { slug: "100m", nome: "100m rasos" },
      { slug: "200m", nome: "200m rasos" },
      { slug: "400m", nome: "400m rasos" },
      { slug: "800m", nome: "800m rasos" },
      { slug: "1500m", nome: "1500m rasos" },
      { slug: "3000m", nome: "3000m rasos" },
      { slug: "rev-4x75m", nome: "Revezamento 4x75m" },
      { slug: "rev-4x100m", nome: "Revezamento 4x100m" },
      { slug: "salto-distancia", nome: "Salto em distância" },
      { slug: "salto-altura", nome: "Salto em altura" },
      { slug: "salto-triplo", nome: "Salto triplo" },
      { slug: "arremesso-peso", nome: "Arremesso de peso" },
      { slug: "lancamento-disco", nome: "Lançamento de disco" },
    ],
    limites_por_escola: {
      "jers-12-14": { masculino: 12, feminino: 12, minimo: null, observacao: "Máx. 2 atletas por prova; até 3 provas individuais + revezamento" },
      "jers-15-17": { masculino: 12, feminino: 12, minimo: null, observacao: "Máx. 2 atletas por prova; até 3 provas individuais + revezamento" },
    },
    desempates: [],
    aliases: ["ATLETISMO", "ATHLETICS"],
  },
  {
    slug: "natacao",
    nome: "Natação",
    tipo: "individual",
    familia: "time",
    formato: "RANK",
    confederacao: "CBDA / World Aquatics",
    categorias: ["nat-12-14", "nat-14-16", "nat-17"],
    naipes: ["Masculino", "Feminino"],
    provas: [
      { slug: "50-livre", nome: "50m livre" },
      { slug: "100-livre", nome: "100m livre" },
      { slug: "200-livre", nome: "200m livre" },
      { slug: "400-livre", nome: "400m livre" },
      { slug: "50-costas", nome: "50m costas" },
      { slug: "100-costas", nome: "100m costas" },
      { slug: "50-peito", nome: "50m peito" },
      { slug: "100-peito", nome: "100m peito" },
      { slug: "50-borboleta", nome: "50m borboleta" },
      { slug: "100-borboleta", nome: "100m borboleta" },
      { slug: "rev-4x50-livre", nome: "Revezamento 4x50m livre" },
    ],
    limites_por_escola: {
      "nat-12-14": { masculino: 10, feminino: 10, minimo: null, observacao: "Até 6 provas individuais + revezamentos" },
      "nat-14-16": { masculino: 10, feminino: 10, minimo: null, observacao: "Até 6 provas individuais + revezamentos" },
      "nat-17": { masculino: 10, feminino: 10, minimo: null, observacao: "Até 6 provas individuais + revezamentos" },
    },
    desempates: [],
    aliases: ["NATACAO", "NATAÇÃO", "SWIMMING"],
  },
  {
    slug: "ciclismo",
    nome: "Ciclismo",
    tipo: "individual",
    familia: "time",
    formato: "RANK",
    confederacao: "CBC",
    categorias: ["jers-12-14", "jers-15-17"],
    naipes: ["Masculino", "Feminino"],
    provas: [
      { slug: "estrada", nome: "Estrada" },
      { slug: "contrarrelogio", nome: "Contrarrelógio" },
    ],
    limites_por_escola: {
      "jers-12-14": { masculino: 3, feminino: 3, minimo: null },
      "jers-15-17": { masculino: 3, feminino: 3, minimo: null },
    },
    partida: {
      rodas: "Tradicionais raiadas de alumínio, mín. 16 raios",
      concentracao: "60 min antes da largada",
    },
    desempates: [],
    aliases: ["CICLISMO", "CYCLING"],
  },
  {
    slug: "aguas-abertas",
    nome: "Águas Abertas",
    tipo: "individual",
    familia: "time",
    formato: "RANK",
    confederacao: "CBDA / World Aquatics",
    categorias: ["nat-12-14", "nat-14-16", "nat-17"],
    naipes: ["Masculino", "Feminino"],
    provas: [{ slug: "prova-unica", nome: "Águas Abertas" }],
    limites_por_escola: {
      "nat-12-14": { masculino: null, feminino: null, minimo: null },
      "nat-14-16": { masculino: null, feminino: null, minimo: null },
      "nat-17": { masculino: null, feminino: null, minimo: null },
    },
    desempates: [],
    aliases: ["AGUAS ABERTAS", "ÁGUAS ABERTAS", "OPEN WATER"],
  },
];
