import type { Modalidade } from "./types";

/** Modalidades de combate (seção 6 do regulamento). */
export const MODALIDADES_COMBATE: Modalidade[] = [
  {
    slug: "judo",
    nome: "Judô",
    tipo: "individual",
    familia: "combat",
    formato: "ELIM+REP",
    confederacao: "CBJ / IJF",
    categorias: ["judo-12-14", "judo-15-16"],
    naipes: ["Masculino", "Feminino"],
    provas: [
      { slug: "combate", nome: "Combate", categorias_peso: [
        { categoria: "judo-12-14", naipe: "Masculino", faixa: "Super Ligeiro até 36kg" },
        { categoria: "judo-12-14", naipe: "Masculino", faixa: "Ligeiro até 40kg" },
        { categoria: "judo-12-14", naipe: "Masculino", faixa: "Meio-leve até 44kg" },
        { categoria: "judo-12-14", naipe: "Masculino", faixa: "Leve até 48kg" },
        { categoria: "judo-12-14", naipe: "Masculino", faixa: "Meio-Médio até 53kg" },
        { categoria: "judo-12-14", naipe: "Masculino", faixa: "Médio até 58kg" },
        { categoria: "judo-12-14", naipe: "Masculino", faixa: "Meio-pesado até 64kg" },
        { categoria: "judo-12-14", naipe: "Masculino", faixa: "Pesado +64kg" },
        { categoria: "judo-12-14", naipe: "Feminino", faixa: "Super Ligeiro até 36kg" },
        { categoria: "judo-12-14", naipe: "Feminino", faixa: "Ligeiro até 40kg" },
        { categoria: "judo-12-14", naipe: "Feminino", faixa: "Meio-leve até 44kg" },
        { categoria: "judo-12-14", naipe: "Feminino", faixa: "Leve até 48kg" },
        { categoria: "judo-12-14", naipe: "Feminino", faixa: "Meio-Médio até 53kg" },
        { categoria: "judo-12-14", naipe: "Feminino", faixa: "Médio até 58kg" },
        { categoria: "judo-12-14", naipe: "Feminino", faixa: "Meio-pesado até 64kg" },
        { categoria: "judo-12-14", naipe: "Feminino", faixa: "Pesado +64kg" },
        { categoria: "judo-15-16", naipe: "Masculino", faixa: "-50kg" },
        { categoria: "judo-15-16", naipe: "Masculino", faixa: "-55kg" },
        { categoria: "judo-15-16", naipe: "Masculino", faixa: "-60kg" },
        { categoria: "judo-15-16", naipe: "Masculino", faixa: "-66kg" },
        { categoria: "judo-15-16", naipe: "Masculino", faixa: "-73kg" },
        { categoria: "judo-15-16", naipe: "Masculino", faixa: "-81kg" },
        { categoria: "judo-15-16", naipe: "Masculino", faixa: "-90kg" },
        { categoria: "judo-15-16", naipe: "Masculino", faixa: "+90kg" },
        { categoria: "judo-15-16", naipe: "Feminino", faixa: "-40kg" },
        { categoria: "judo-15-16", naipe: "Feminino", faixa: "-44kg" },
        { categoria: "judo-15-16", naipe: "Feminino", faixa: "-48kg" },
        { categoria: "judo-15-16", naipe: "Feminino", faixa: "-52kg" },
        { categoria: "judo-15-16", naipe: "Feminino", faixa: "-57kg" },
        { categoria: "judo-15-16", naipe: "Feminino", faixa: "-63kg" },
        { categoria: "judo-15-16", naipe: "Feminino", faixa: "-70kg" },
        { categoria: "judo-15-16", naipe: "Feminino", faixa: "+70kg" },
      ]},
    ],
    limites_por_escola: {
      "judo-12-14": { masculino: 10, feminino: 10, minimo: null, observacao: "1 atleta por categoria de peso" },
      "judo-15-16": { masculino: 10, feminino: 10, minimo: null, observacao: "1 atleta por categoria de peso" },
    },
    minimo_para_categoria: 2,
    partida: {
      duracao: "4 min (todas as categorias)",
      vitoria: ["Ippon", "2 Waza-ari", "3 Shidos do adversário (Hansoku-make)"],
      empate: "Golden Score (tempo extra ilimitado)",
      terceiro_lugar: "Bronze duplo",
      graduacao_min_12_14: "Faixa azul",
      graduacao_min_15_16: "Faixa laranja",
      pesagem: "Dia anterior, aferição única, sunga (masc.) / collant (fem.)",
    },
    desempates: [],
    aliases: ["JUDO", "JUDÔ"],
  },
  {
    slug: "karate",
    nome: "Karatê",
    tipo: "individual",
    familia: "combat",
    formato: "SE",
    confederacao: "CBKC / WKF",
    categorias: ["jers-12-14", "jers-15-17"],
    naipes: ["Masculino", "Feminino"],
    provas: [
      { slug: "kumite", nome: "Kumite", categorias_peso: [
        { categoria: "jers-12-14", naipe: "Masculino", faixa: "-45kg" },
        { categoria: "jers-12-14", naipe: "Masculino", faixa: "-52kg" },
        { categoria: "jers-12-14", naipe: "Masculino", faixa: "-63kg" },
        { categoria: "jers-12-14", naipe: "Masculino", faixa: "+63kg" },
        { categoria: "jers-12-14", naipe: "Feminino", faixa: "-42kg" },
        { categoria: "jers-12-14", naipe: "Feminino", faixa: "-47kg" },
        { categoria: "jers-12-14", naipe: "Feminino", faixa: "-54kg" },
        { categoria: "jers-12-14", naipe: "Feminino", faixa: "+54kg" },
        { categoria: "jers-15-17", naipe: "Masculino", faixa: "-61kg" },
        { categoria: "jers-15-17", naipe: "Masculino", faixa: "-68kg" },
        { categoria: "jers-15-17", naipe: "Masculino", faixa: "-76kg" },
        { categoria: "jers-15-17", naipe: "Masculino", faixa: "+76kg" },
        { categoria: "jers-15-17", naipe: "Feminino", faixa: "-48kg" },
        { categoria: "jers-15-17", naipe: "Feminino", faixa: "-53kg" },
        { categoria: "jers-15-17", naipe: "Feminino", faixa: "-59kg" },
        { categoria: "jers-15-17", naipe: "Feminino", faixa: "+59kg" },
      ]},
      { slug: "kata", nome: "Kata" },
    ],
    limites_por_escola: {
      "jers-12-14": { masculino: 10, feminino: 10, minimo: null, observacao: "Pode inscrever em kata E kumite" },
      "jers-15-17": { masculino: 10, feminino: 10, minimo: null, observacao: "Pode inscrever em kata E kumite" },
    },
    minimo_para_categoria: 2,
    partida: {
      duracao_kumite: "2 min (Shobu, diferença de 8 pts)",
      area: "8 × 8 metros",
      pontuacao: "Sanbon: 3 pts · Nihon: 2 pts · Ippon: 1 pt",
      contato_jodan: "Superficial",
      contato_chudan: "Normal",
      terceiro_lugar: "2 terceiros (perdedores das semis)",
      graduacao_min: "6º kyu",
      tolerancia_pesagem: "500g",
    },
    desempates: [],
    aliases: ["KARATE", "KARATÊ"],
  },
  {
    slug: "taekwondo",
    nome: "Taekwondo",
    tipo: "individual",
    familia: "combat",
    formato: "ELIM+REP",
    confederacao: "CBTKD / WT",
    categorias: ["jers-12-14", "jers-15-17"],
    naipes: ["Masculino", "Feminino"],
    provas: [
      { slug: "kyorugi", nome: "Combate (Kyorugi)" },
      { slug: "poomsae", nome: "Poomsae (Forma)" },
    ],
    limites_por_escola: {
      "jers-12-14": { masculino: 10, feminino: 10, minimo: null, observacao: "Até 4 atletas por categoria de peso" },
      "jers-15-17": { masculino: 10, feminino: 10, minimo: null, observacao: "Até 4 atletas por categoria de peso" },
    },
    minimo_para_categoria: 2,
    partida: {
      duracao_12_14: "2 rounds × 2 min, intervalo 1 min",
      duracao_15_17: "3 rounds × 2 min, intervalo 1 min",
      chute_cabeca_12_14: "PROIBIDO",
      chute_cabeca_15_17: "PERMITIDO",
      pontuacao: "Soco tronco 1 · Chute tronco 2 · Chute cabeça 3 · Giratório tronco 4 · Giratório cabeça 5",
      penalidade: "Gam-jeom: -1 pt",
      vitoria: "Maior pontuação · RSC (20 pts) · Nocaute",
      empate: "Golden Point",
      graduacao_12_14: "Máxima 3º GUB",
      graduacao_15_17: "Mínima 4º GUB",
    },
    desempates: [],
    aliases: ["TAEKWONDO", "TAE KWON DO", "TKD"],
  },
  {
    slug: "wrestling",
    nome: "Wrestling",
    tipo: "individual",
    familia: "combat",
    formato: "ELIM+REP",
    confederacao: "CBW / UWW",
    categorias: ["wrestling-12-14", "wrestling-14-16"],
    naipes: ["Masculino", "Feminino"],
    provas: [
      { slug: "livre-masc", nome: "Estilo Livre Masculino" },
      { slug: "livre-fem", nome: "Estilo Livre Feminino" },
      { slug: "greco-romano", nome: "Greco-Romano Masculino" },
    ],
    limites_por_escola: {
      "wrestling-12-14": { masculino: 10, feminino: 10, minimo: null, observacao: "1 atleta por categoria de peso por estilo" },
      "wrestling-14-16": { masculino: 10, feminino: 10, minimo: null, observacao: "1 atleta por categoria de peso por estilo" },
    },
    minimo_para_categoria: 2,
    partida: {
      combate_sub_14: "2 × 2 min, intervalo 30s",
      combate_sub_16: "2 × 3 min, intervalo 30s",
      sup_tecnica_livre: "10 pts",
      sup_tecnica_greco: "8 pts",
      tolerancia_pesagem: "500g",
      pesagem: "2 dias antes, janela 3h, aferição única",
      pesagem_remota: "Permitida excepcionalmente para atletas do interior",
      formato_2_atletas: "Melhor de 3 combates",
      formato_3_4: "Round Robin",
      formato_5_8: "Eliminatório com repescagem",
      formato_9_mais: "Eliminatório com repescagem e chaves",
    },
    desempates: [
      { ordem: 1, criterio: "Maior número de vitórias" },
      { ordem: 2, criterio: "Maior número de vitórias por superioridade técnica" },
      { ordem: 3, criterio: "Maior número de vitórias por encostamento (fall)" },
      { ordem: 4, criterio: "Maior diferença de pontos técnicos" },
      { ordem: 5, criterio: "Menor número de pontos técnicos sofridos" },
    ],
    aliases: ["WRESTLING", "LUTA OLIMPICA", "LUTA OLÍMPICA"],
  },
];
