import type { Modalidade } from "./types";

/** Modalidades paralímpicas (seção 9 do regulamento — JERPA). */
export const MODALIDADES_PARALIMPICAS: Modalidade[] = [
  {
    slug: "atletismo-paralimpico",
    nome: "Atletismo Paralímpico",
    tipo: "individual_paralimpica",
    familia: "time",
    formato: "RANK",
    confederacao: "CBCA / World Para Athletics",
    categorias: ["jerpa-11-14", "jerpa-15-17"],
    naipes: ["Masculino", "Feminino"],
    provas: [
      { slug: "75m", nome: "75m rasos" },
      { slug: "100m", nome: "100m rasos" },
      { slug: "150m", nome: "150m rasos" },
      { slug: "200m", nome: "200m rasos" },
      { slug: "400m", nome: "400m rasos" },
      { slug: "800m", nome: "800m rasos" },
      { slug: "2000m", nome: "2000m rasos" },
      { slug: "3000m", nome: "3000m rasos" },
      { slug: "salto-distancia", nome: "Salto em distância" },
      { slug: "arremesso-peso", nome: "Arremesso de peso" },
      { slug: "lancamento-dardo", nome: "Lançamento de dardo" },
      { slug: "lancamento-disco", nome: "Lançamento de disco" },
      { slug: "lancamento-club", nome: "Lançamento de club" },
    ],
    limites_por_escola: {
      "jerpa-11-14": { masculino: 12, feminino: 12, minimo: null },
      "jerpa-15-17": { masculino: 12, feminino: 12, minimo: null },
    },
    partida: {
      criterio: "Menor tempo (pista) · Maior marca (campo)",
      atleta_guia: "Permitido nas classes T11–T12",
      empate: "Ambos recebem mesma medalha",
      classes_pista: ["T11", "T12", "T13", "T20", "T31-T34", "T35-T38", "T40-T41", "T42-T44", "T45-T47", "T51-T54", "T61-T64", "RR1-RR3"],
      classes_campo: ["F11-F13", "F20", "F31-F38", "F40-F41", "F42-F44", "F45-F47", "F51-F54"],
    },
    desempates: [],
    aliases: ["ATLETISMO PARALIMPICO", "ATLETISMO PARALÍMPICO"],
  },
  {
    slug: "natacao-paralimpica",
    nome: "Natação Paralímpica",
    tipo: "individual_paralimpica",
    familia: "time",
    formato: "RANK",
    confederacao: "CBCA / World Para Swimming",
    categorias: ["jerpa-11-14", "jerpa-15-17"],
    naipes: ["Masculino", "Feminino"],
    provas: [{ slug: "prova-classe", nome: "Prova por classe funcional" }],
    limites_por_escola: {
      "jerpa-11-14": { masculino: 10, feminino: 10, minimo: null },
      "jerpa-15-17": { masculino: 10, feminino: 10, minimo: null },
    },
    partida: {
      classes: "S1–S14 (físico, visual, intelectual)",
      toque_parede: "Adaptado (S11–S13: tappers)",
    },
    desempates: [],
    aliases: ["NATACAO PARALIMPICA", "NATAÇÃO PARALÍMPICA"],
  },
  {
    slug: "tenis-de-mesa-paralimpico",
    nome: "Tênis de Mesa Paralímpico",
    tipo: "individual_paralimpica",
    familia: "sets",
    formato: "GP+SE",
    confederacao: "CBTM / ITTF Para",
    categorias: ["jerpa-11-14", "jerpa-15-17"],
    naipes: ["Masculino", "Feminino"],
    provas: [
      { slug: "andantes-cat-a", nome: "Andantes Categoria A" },
      { slug: "andantes-cat-b", nome: "Andantes Categoria B" },
      { slug: "cadeirantes-cat-a", nome: "Cadeirantes Categoria A" },
      { slug: "cadeirantes-cat-b", nome: "Cadeirantes Categoria B" },
      { slug: "intelectual", nome: "Deficiência Intelectual (Classe 11)" },
    ],
    limites_por_escola: {
      "jerpa-11-14": { masculino: 6, feminino: 6, minimo: null, observacao: "2 andantes + 2 cadeirantes + 2 intelectuais por gênero" },
      "jerpa-15-17": { masculino: 6, feminino: 6, minimo: null, observacao: "2 andantes + 2 cadeirantes + 2 intelectuais por gênero" },
    },
    pontuacao_grupos: { vitoria: 2, derrota: 1, wo: 0 },
    partida: {
      classificatoria: "Melhor de 3 sets a 11 pts (vant. 2)",
      eliminatoria: "Melhor de 5 sets a 11 pts (vant. 2)",
      classes_cadeirantes: "1-2 e 3-5",
      classes_andantes: "6-8 e 9-10",
      classe_intelectual: "11",
    },
    desempates: [],
    aliases: ["TENIS DE MESA PARALIMPICO", "TÊNIS DE MESA PARALÍMPICO", "TM PARALIMPICO"],
  },
  {
    slug: "parabadminton",
    nome: "Parabadminton",
    tipo: "individual_paralimpica",
    familia: "sets",
    formato: "GP+SE",
    confederacao: "CBBd / BWF Para",
    categorias: ["jerpa-11-14", "jerpa-15-17"],
    naipes: ["Masculino", "Feminino"],
    provas: [
      { slug: "simples-masc", nome: "Simples Masculino" },
      { slug: "simples-fem", nome: "Simples Feminino" },
    ],
    limites_por_escola: {
      "jerpa-11-14": { masculino: 20, feminino: 20, minimo: null },
      "jerpa-15-17": { masculino: 20, feminino: 20, minimo: null },
    },
    partida: {
      formato: "Melhor de 3 games a 21 pts (vant. 2; limite 30×29)",
      grupos: "Mín. 3, máx. 4 atletas",
      classes: ["WH", "SL", "SU", "SH", "SI"],
      observacao: "Classes podem ser combinadas se poucas inscrições (exceto SH)",
    },
    desempates: [],
    aliases: ["PARABADMINTON", "PARA BADMINTON"],
  },
  {
    slug: "bocha-paralimpica",
    nome: "Bocha Paralímpica",
    tipo: "individual_paralimpica",
    familia: "score",
    formato: "GP+SE",
    confederacao: "ABBC / BISFed",
    categorias: ["jerpa-11-14", "jerpa-15-17"],
    naipes: ["Masculino", "Feminino"],
    provas: [
      { slug: "bc1", nome: "BC1 — cadeirante com auxílio" },
      { slug: "bc2", nome: "BC2 — cadeirante sem auxílio" },
      { slug: "bc3", nome: "BC3 — rampa" },
      { slug: "bc4", nome: "BC4 — cadeirante, outros" },
    ],
    limites_por_escola: {
      "jerpa-11-14": { masculino: 4, feminino: 4, minimo: null },
      "jerpa-15-17": { masculino: 4, feminino: 4, minimo: null },
    },
    partida: {
      formato_individual: "4 ends",
      pontuacao_end: "Bolas do vencedor mais próximas ao jack",
      empate_final: "End extra (golden end)",
      cadeira_max: "66 cm (exceto BC3)",
      calhas: "Devem caber no box 2,5m × 1,0m; sem mira, freio ou propulsão mecânica",
    },
    desempates: [],
    aliases: ["BOCHA PARALIMPICA", "BOCHA PARALÍMPICA", "BOCCIA"],
  },
];
