import type { SportEventRulesV1 } from "@/types/sportEventRules";

export interface SportPreset {
  key: string;
  label: string;
  description: string;
  category?: "coletiva" | "combate" | "tempo_marca" | "sets" | "ranking" | "paralimpica";
  rules: SportEventRulesV1 & Record<string, unknown>;
}

const OP_RULES = { wxo_minutes: 15, wo_refusal_minutes: 5 };

export const SPORT_PRESET_CATALOG: SportPreset[] = [
  // ═══════════════════════════════════════════════
  // 3.1 COLETIVAS (JER)
  // ═══════════════════════════════════════════════
  {
    key: "FUTSAL",
    label: "Futsal",
    category: "coletiva",
    description: "Placar (gols), GP+SE, W.O. 3×0, prorrogação 2×5min + penalidades 3+alternadas",
    rules: {
      family: "score",
      format: "group_stage",
      participant_mode: "team",
      scoring: { score_type: "goals", walkover_policy: { home_goals: 3, away_goals: 0 } },
      scheduling: {},
      tie_breakers: ["head_to_head", "goal_average", "goals_for", "goals_against", "yellow_cards", "red_cards", "draw"],
      enrollment_limits: {},
      group_points: { win: 3, draw: 1, loss: 0, wo_win: 3, wo_loss: 0 },
      knockout_tie_resolution: {
        type: "overtime_plus_penalties",
        overtime_periods: 2,
        overtime_minutes: 5,
        penalties: { initial_kicks: 3, mode: "alternating" },
      },
      operational_rules: OP_RULES,
      preset_key: "FUTSAL",
    },
  },
  {
    key: "FUTEBOL",
    label: "Futebol de Campo",
    category: "coletiva",
    description: "Placar (gols), GP+SE, W.O. 3×0, penalidades 5+alternadas, desempate c/ disciplina",
    rules: {
      family: "score",
      format: "group_stage",
      participant_mode: "team",
      scoring: { score_type: "goals", walkover_policy: { home_goals: 3, away_goals: 0 } },
      scheduling: {},
      tie_breakers: ["head_to_head", "goal_average", "goal_difference", "goals_for", "yellow_cards", "red_cards", "draw"],
      enrollment_limits: {},
      group_points: { win: 3, draw: 1, loss: 0, wo_win: 3, wo_loss: 0 },
      knockout_tie_resolution: { type: "penalties", initial_kicks: 5, mode: "alternating" },
      operational_rules: OP_RULES,
      preset_key: "FUTEBOL",
    },
  },
  {
    key: "HANDEBOL",
    label: "Handebol",
    category: "coletiva",
    description: "Placar (gols), GP+SE, W.O. 10×0, prorrogação 2×5min + penalidades 5",
    rules: {
      family: "score",
      format: "group_stage",
      participant_mode: "team",
      scoring: { score_type: "goals", walkover_policy: { home_goals: 10, away_goals: 0 } },
      scheduling: {},
      tie_breakers: ["head_to_head", "wins", "goal_average", "goals_against", "goals_for", "goal_difference", "draw"],
      enrollment_limits: {},
      group_points: { win: 2, draw: 1, loss: 0, wo_win: 2, wo_loss: 0 },
      knockout_tie_resolution: {
        type: "overtime_plus_shootout",
        overtime_periods: 2,
        overtime_minutes: 5,
        shootout: { type: "7m", initial_kicks: 5, mode: "alternating" },
      },
      operational_rules: OP_RULES,
      preset_key: "HANDEBOL",
    },
  },
  {
    key: "BASQUETEBOL",
    label: "Basquetebol",
    category: "coletiva",
    description: "Placar (pontos), GP+SE, W.O. 20×0, prorrogação 5min até decisão",
    rules: {
      family: "score",
      format: "group_stage",
      participant_mode: "team",
      scoring: { score_type: "points", walkover_policy: { home_points: 20, away_points: 0 } },
      scheduling: {},
      tie_breakers: ["head_to_head", "points_quotient_between", "points_quotient_overall", "points_for", "draw"],
      enrollment_limits: {},
      group_points: { win: 2, loss: 1, wo_win: 2, wo_loss: 0 },
      knockout_tie_resolution: { type: "overtime", overtime_minutes: 5, repeat_until_winner: true },
      operational_rules: OP_RULES,
      preset_key: "BASQUETEBOL",
    },
  },
  {
    key: "VOLEIBOL",
    label: "Voleibol",
    category: "coletiva",
    description: "Sets (best-of 5), GP+SE, W.O. 3×0 (25×0), pontuação variável por resultado",
    rules: {
      family: "sets",
      format: "group_stage",
      participant_mode: "team",
      scoring: {
        score_type: "rally_points",
        best_of: 5,
        set_points: 25,
        walkover_policy: { sets: "3-0", set_scores: ["25-0", "25-0", "25-0"] },
      },
      scheduling: {},
      tie_breakers: ["points_table", "sets_quotient", "points_quotient", "head_to_head_recalc", "draw"],
      enrollment_limits: {},
      group_points: {
        win: 0, draw: 0, loss: 0,
        special: {
          "3-0": { winner: 3, loser: 0 },
          "3-1": { winner: 3, loser: 0 },
          "3-2": { winner: 2, loser: 1 },
        },
      },
      sets_policy: { set_1_4: 25, set_5: 15, win_by_2: true },
      operational_rules: OP_RULES,
      preset_key: "VOLEIBOL",
    },
  },
  {
    key: "VOLEI_DE_PRAIA_12_14",
    label: "Vôlei de Praia (12–14)",
    category: "coletiva",
    description: "Sets (best-of 3), duplas, RR + eliminatória, sets 21/21/15",
    rules: {
      family: "sets",
      format: "round_robin",
      participant_mode: "pair",
      scoring: { score_type: "rally_points", best_of: 3, set_points: 21, walkover_policy: { sets: "2-0" } },
      scheduling: {},
      tie_breakers: ["sets_quotient", "points_quotient", "draw"],
      enrollment_limits: {},
      group_points: {
        win: 0, draw: 0, loss: 0,
        special: { "2-0": { winner: 3, loser: 0 }, "2-1": { winner: 2, loser: 1 } },
      },
      sets_policy: { set_1_2: 21, set_3: 15, win_by_2: true },
      allow_knockout: true,
      operational_rules: OP_RULES,
      preset_key: "VOLEI_DE_PRAIA_12_14",
    },
  },
  {
    key: "VOLEI_DE_PRAIA_15_17",
    label: "Vôlei de Praia (15–17)",
    category: "coletiva",
    description: "Sets (best-of 3), duplas por escola, GP + eliminatória, sets 21/21/15",
    rules: {
      family: "sets",
      format: "group_stage",
      participant_mode: "pair",
      scoring: { score_type: "rally_points", best_of: 3, set_points: 21, walkover_policy: { sets: "2-0" } },
      scheduling: {},
      tie_breakers: ["sets_quotient", "points_quotient", "draw"],
      enrollment_limits: {},
      group_points: {
        win: 0, draw: 0, loss: 0,
        special: { "2-0": { winner: 3, loser: 0 }, "2-1": { winner: 2, loser: 1 } },
      },
      sets_policy: { set_1_2: 21, set_3: 15, win_by_2: true },
      allow_knockout: true,
      operational_rules: OP_RULES,
      preset_key: "VOLEI_DE_PRAIA_15_17",
    },
  },

  // ═══════════════════════════════════════════════
  // 3.2 COMBATE (JER)
  // ═══════════════════════════════════════════════
  {
    key: "JUDO",
    label: "Judô",
    category: "combate",
    description: "Combate, chave eliminatória c/ repescagem (olímpico), golden score, 2 terceiros",
    rules: {
      family: "combat",
      format: "combat_bracket",
      participant_mode: "individual",
      scoring: { score_type: "combat_points" },
      scheduling: {},
      tie_breakers: [],
      enrollment_limits: {},
      medals_policy: { third_places: 2, repechage: true },
      combat_policy: { golden_score: true, time_by_category: true },
      operational_rules: OP_RULES,
      preset_key: "JUDO",
    },
  },
  {
    key: "KARATE_KATA",
    label: "Karatê — Kata",
    category: "combate",
    description: "Ranking por nota de juízes, bandeiras/pontuação, 2 terceiros",
    rules: {
      family: "ranking",
      format: "ranking",
      participant_mode: "individual",
      scoring: { score_type: "placement_points" },
      scheduling: {},
      tie_breakers: [],
      enrollment_limits: {},
      ranking_policy: { type: "judges", allow_ties: false, third_places: 2 },
      medals_policy: { third_places: 2, repechage: null },
      kata_rules: { no_repeat_each_round: true },
      operational_rules: OP_RULES,
      preset_key: "KARATE_KATA",
    },
  },
  {
    key: "KARATE_KUMITE",
    label: "Karatê — Kumite",
    category: "combate",
    description: "Combate, chave eliminatória, 2 min, senshu, diff 8 pts, 2 terceiros",
    rules: {
      family: "combat",
      format: "combat_bracket",
      participant_mode: "individual",
      scoring: { score_type: "combat_points" },
      scheduling: {},
      tie_breakers: [],
      enrollment_limits: {},
      medals_policy: { third_places: 2, repechage: false },
      combat_policy: { fight_minutes: 2, win_by_point_diff: 8, senshu: true, third_places: 2 },
      operational_rules: OP_RULES,
      notes: "Repescagem conforme regulamento específico do evento.",
      preset_key: "KARATE_KUMITE",
    },
  },
  {
    key: "TAEKWONDO",
    label: "Taekwondo",
    category: "combate",
    description: "Combate, chave eliminatória c/ repescagem, golden point, 2 terceiros",
    rules: {
      family: "combat",
      format: "combat_bracket",
      participant_mode: "individual",
      scoring: { score_type: "combat_points" },
      scheduling: {},
      tie_breakers: [],
      enrollment_limits: {},
      medals_policy: { third_places: 2, repechage: true },
      combat_policy: { rounds: 3, round_minutes: 2, golden_point: true },
      operational_rules: OP_RULES,
      preset_key: "TAEKWONDO",
    },
  },
  {
    key: "WRESTLING",
    label: "Wrestling (Luta Olímpica)",
    category: "combate",
    description: "Combate, chave eliminatória c/ repescagem, tech fall diff 10, 2 terceiros",
    rules: {
      family: "combat",
      format: "combat_bracket",
      participant_mode: "individual",
      scoring: { score_type: "combat_points" },
      scheduling: {},
      tie_breakers: [],
      enrollment_limits: {},
      medals_policy: { third_places: 2, repechage: true },
      combat_policy: { tech_fall_diff: 10, pin: true, periods: 2, period_minutes: 3 },
      operational_rules: OP_RULES,
      preset_key: "WRESTLING",
    },
  },

  // ═══════════════════════════════════════════════
  // 3.3 TEMPO / MARCA (JER)
  // ═══════════════════════════════════════════════
  {
    key: "ATLETISMO_PISTA",
    label: "Atletismo — Pista",
    category: "tempo_marca",
    description: "Tempo (ms), baterias + final, 8 raias, ranking por tempo",
    rules: {
      family: "time",
      format: "heats_final",
      participant_mode: "individual",
      scoring: { score_type: "time_ms" },
      scheduling: { lanes_min: 6, lanes_max: 8 },
      tie_breakers: [],
      enrollment_limits: {},
      ranking_policy: { type: "time" },
      operational_rules: OP_RULES,
      preset_key: "ATLETISMO_PISTA",
    },
  },
  {
    key: "ATLETISMO_CAMPO",
    label: "Atletismo — Campo",
    category: "tempo_marca",
    description: "Marca (cm), ranking por distância, 3+3 tentativas",
    rules: {
      family: "mark",
      format: "ranking",
      participant_mode: "individual",
      scoring: { score_type: "distance_cm" },
      scheduling: {},
      tie_breakers: [],
      enrollment_limits: {},
      ranking_policy: { type: "mark" },
      attempts_policy: { qualifying: 3, final: 3 },
      operational_rules: OP_RULES,
      preset_key: "ATLETISMO_CAMPO",
    },
  },
  {
    key: "ATLETISMO_COMBINADAS",
    label: "Atletismo — Provas Combinadas",
    category: "tempo_marca",
    description: "Ranking por pontuação combinada (tabelas IAAF), pentatlo/hexatlo",
    rules: {
      family: "ranking",
      format: "ranking",
      participant_mode: "individual",
      scoring: { score_type: "placement_points" },
      scheduling: {},
      tie_breakers: [],
      enrollment_limits: {},
      ranking_policy: { type: "combined_points", tables: "IAAF" },
      operational_rules: OP_RULES,
      preset_key: "ATLETISMO_COMBINADAS",
    },
  },
  {
    key: "NATACAO",
    label: "Natação",
    category: "tempo_marca",
    description: "Tempo (ms), baterias + final, 6–10 raias, empate: ambos avançam",
    rules: {
      family: "time",
      format: "heats_final",
      participant_mode: "individual",
      scoring: { score_type: "time_ms" },
      scheduling: { lanes_min: 6, lanes_max: 10 },
      tie_breakers: [],
      enrollment_limits: {},
      ranking_policy: { type: "time", tie_advance_both: true },
      operational_rules: OP_RULES,
      preset_key: "NATACAO",
    },
  },
  {
    key: "CICLISMO",
    label: "Ciclismo",
    category: "tempo_marca",
    description: "Tempo total, ranking direto ou baterias (CRI)",
    rules: {
      family: "time",
      format: "ranking",
      participant_mode: "individual",
      scoring: { score_type: "time_ms" },
      scheduling: {},
      tie_breakers: [],
      enrollment_limits: {},
      ranking_policy: { type: "time_total" },
      operational_rules: OP_RULES,
      preset_key: "CICLISMO",
    },
  },

  // ═══════════════════════════════════════════════
  // 3.4 CONFRONTO TÉCNICO / SETS (JER)
  // ═══════════════════════════════════════════════
  {
    key: "BADMINTON",
    label: "Badminton",
    category: "sets",
    description: "Sets (best-of 3), game to 21 (cap 30), GP ou RR, pontos 2/1/0",
    rules: {
      family: "sets",
      format: "group_stage",
      participant_mode: "individual",
      scoring: { score_type: "rally_points", best_of: 3, set_points: 21 },
      scheduling: {},
      tie_breakers: ["head_to_head", "games_quotient", "points_quotient", "draw"],
      enrollment_limits: {},
      group_points: { win: 2, loss: 1, wo_win: 2, wo_loss: 0 },
      sets_policy: { game_to: 21, cap: 30, win_by_2: true },
      allow_rr_if_few: true,
      operational_rules: OP_RULES,
      preset_key: "BADMINTON",
    },
  },
  {
    key: "TENIS_DE_MESA",
    label: "Tênis de Mesa",
    category: "sets",
    description: "Sets (best-of 5), game to 11, GP ou RR, pontos 2/1/0",
    rules: {
      family: "sets",
      format: "group_stage",
      participant_mode: "individual",
      scoring: { score_type: "rally_points", best_of: 5, set_points: 11 },
      scheduling: {},
      tie_breakers: ["head_to_head", "games_quotient", "points_quotient", "draw"],
      enrollment_limits: {},
      group_points: { win: 2, loss: 1, wo_win: 2, wo_loss: 0 },
      sets_policy: { game_to: 11, win_by_2: true },
      allow_rr_if_few: true,
      operational_rules: OP_RULES,
      preset_key: "TENIS_DE_MESA",
    },
  },
  {
    key: "TIRO_COM_ARCO",
    label: "Tiro com Arco",
    category: "sets",
    description: "Set system, ranking round 72 flechas + eliminatória set first-to-6, shoot-off",
    rules: {
      family: "sets",
      format: "knockout",
      participant_mode: "individual",
      scoring: { score_type: "points", best_of: null, set_points: null },
      scheduling: {},
      tie_breakers: [],
      enrollment_limits: {},
      archery_policy: { ranking_round: "72_arrows", elimination_set_system_first_to: 6, shoot_off: true },
      operational_rules: OP_RULES,
      preset_key: "TIRO_COM_ARCO",
    },
  },

  // ═══════════════════════════════════════════════
  // 3.5 RANKING / NOTA (JER)
  // ═══════════════════════════════════════════════
  {
    key: "XADREZ",
    label: "Xadrez",
    category: "ranking",
    description: "Sistema suíço, pontuação de partidas, desempate Buchholz/SB",
    rules: {
      family: "ranking",
      format: "swiss",
      participant_mode: "individual",
      scoring: { score_type: "placement_points" },
      scheduling: {},
      tie_breakers: ["buchholz", "buchholz_cut", "sonneborn_berger", "wins", "head_to_head", "draw"],
      enrollment_limits: {},
      ranking_policy: { type: "swiss" },
      operational_rules: OP_RULES,
      preset_key: "XADREZ",
    },
  },
  {
    key: "GINASTICA_RITMICA",
    label: "Ginástica Rítmica",
    category: "ranking",
    description: "Ranking por nota (D+E−penalidades), juízes, sem confronto direto",
    rules: {
      family: "ranking",
      format: "ranking",
      participant_mode: "individual",
      scoring: { score_type: "placement_points" },
      scheduling: {},
      tie_breakers: ["D_total", "E_total", "penalties_total"],
      enrollment_limits: {},
      ranking_policy: { type: "judges", formula: "D+E-penalties" },
      operational_rules: OP_RULES,
      preset_key: "GINASTICA_RITMICA",
    },
  },

  // ═══════════════════════════════════════════════
  // 3.6 JERPA — PARALÍMPICAS
  // ═══════════════════════════════════════════════
  {
    key: "ATLETISMO_PARALIMPICO",
    label: "Atletismo Paralímpico",
    category: "paralimpica",
    description: "Tempo/marca, baterias + final, classificação funcional obrigatória",
    rules: {
      family: "time",
      format: "heats_final",
      participant_mode: "individual",
      scoring: { score_type: "time_ms" },
      scheduling: { lanes_min: 4, lanes_max: 8 },
      tie_breakers: [],
      enrollment_limits: {},
      ranking_policy: { type: "time" },
      disability_policy: { class_required: true, class_field: "functional_class" },
      operational_rules: OP_RULES,
      preset_key: "ATLETISMO_PARALIMPICO",
    },
  },
  {
    key: "NATACAO_PARALIMPICA",
    label: "Natação Paralímpica",
    category: "paralimpica",
    description: "Tempo (ms), baterias + final, classificação funcional obrigatória",
    rules: {
      family: "time",
      format: "heats_final",
      participant_mode: "individual",
      scoring: { score_type: "time_ms" },
      scheduling: { lanes_min: 4, lanes_max: 8 },
      tie_breakers: [],
      enrollment_limits: {},
      ranking_policy: { type: "time" },
      disability_policy: { class_required: true, class_field: "functional_class" },
      operational_rules: OP_RULES,
      preset_key: "NATACAO_PARALIMPICA",
    },
  },
  {
    key: "TENIS_DE_MESA_PARALIMPICO",
    label: "Tênis de Mesa Paralímpico",
    category: "paralimpica",
    description: "Sets (best-of 5), game to 11, GP + eliminatória, classificação funcional",
    rules: {
      family: "sets",
      format: "group_stage",
      participant_mode: "individual",
      scoring: { score_type: "rally_points", best_of: 5, set_points: 11 },
      scheduling: {},
      tie_breakers: ["head_to_head", "games_quotient", "points_quotient", "draw"],
      enrollment_limits: {},
      group_points: { win: 2, loss: 1, wo_win: 2, wo_loss: 0 },
      disability_policy: { class_required: true, class_field: "functional_class" },
      operational_rules: OP_RULES,
      preset_key: "TENIS_DE_MESA_PARALIMPICO",
    },
  },
  {
    key: "PARABADMINTON",
    label: "Parabadminton",
    category: "paralimpica",
    description: "Sets (best-of 3), game to 21, classificação funcional obrigatória",
    rules: {
      family: "sets",
      format: "group_stage",
      participant_mode: "individual",
      scoring: { score_type: "rally_points", best_of: 3, set_points: 21 },
      scheduling: {},
      tie_breakers: ["head_to_head", "games_quotient", "points_quotient", "draw"],
      enrollment_limits: {},
      group_points: { win: 2, loss: 1, wo_win: 2, wo_loss: 0 },
      disability_policy: { class_required: true, class_field: "functional_class" },
      operational_rules: OP_RULES,
      preset_key: "PARABADMINTON",
    },
  },
  {
    key: "BOCHA_PARALIMPICA",
    label: "Bocha Paralímpica",
    category: "paralimpica",
    description: "Placar (ends), GP + eliminatória, golden end, classificação funcional",
    rules: {
      family: "score",
      format: "group_stage",
      participant_mode: "individual",
      scoring: { score_type: "points" },
      scheduling: {},
      tie_breakers: [],
      enrollment_limits: {},
      group_points: { win: 2, loss: 0, wo_win: 2, wo_loss: 0 },
      boccia_policy: { ends_individual: 4, ends_team: 6, golden_end_on_tie: true },
      disability_policy: { class_required: true, class_field: "functional_class" },
      operational_rules: OP_RULES,
      preset_key: "BOCHA_PARALIMPICA",
    },
  },
];

export function getPresetByKey(key: string): SportPreset | undefined {
  return SPORT_PRESET_CATALOG.find((p) => p.key === key);
}

export const PRESET_CATEGORIES: { value: string; label: string }[] = [
  { value: "coletiva", label: "Coletivas" },
  { value: "combate", label: "Combate/Lutas" },
  { value: "tempo_marca", label: "Tempo/Marca" },
  { value: "sets", label: "Sets/Confronto Técnico" },
  { value: "ranking", label: "Ranking/Nota" },
  { value: "paralimpica", label: "Paralímpicas (JERPA)" },
];
