import type { Database } from "@/integrations/supabase/types";

export enum ModuleStatus {
  DONE = "done",
  PARTIAL = "partial",
  NOT_STARTED = "not_started",
}

export const STATUS_META: Record<ModuleStatus, { label: string; emoji: string; color: string }> = {
  [ModuleStatus.DONE]: { label: "Feito", emoji: "✅", color: "bg-green-100 text-green-800 border-green-300" },
  [ModuleStatus.PARTIAL]: { label: "Parcial", emoji: "🟡", color: "bg-yellow-100 text-yellow-800 border-yellow-300" },
  [ModuleStatus.NOT_STARTED]: { label: "Não iniciado", emoji: "⛔", color: "bg-red-100 text-red-800 border-red-300" },
};

export type AppRole = Database["public"]["Enums"]["app_role"];

export interface SystemMapItem {
  id: string;
  label: string;
  route: string;
  pageFile: string;
  description: string;
  roles: AppRole[];
  status: ModuleStatus;
  dataSources: string[];
  gaps: string[];
  nextActions: string[];
}

export interface SystemMapGroup {
  id: string;
  label: string;
  items: SystemMapItem[];
  subGroups?: { label: string; items: SystemMapItem[] }[];
}

export const systemMap: SystemMapGroup[] = [
  {
    id: "dashboard",
    label: "Dashboard",
    items: [
      {
        id: "dashboard",
        label: "Dashboard",
        route: "/admin",
        pageFile: "src/pages/admin/DashboardPage.tsx",
        description: "Painel principal do administrador com visão geral do evento ativo, KPIs e atalhos rápidos.",
        roles: ["admin", "secretaria", "coordenacao_tecnica", "coordenador_modalidade"],
        status: ModuleStatus.DONE,
        dataSources: ["events"],
        gaps: [],
        nextActions: [],
      },
    ],
  },
  {
    id: "preparacao",
    label: "Preparação",
    items: [
      {
        id: "eventos",
        label: "Eventos",
        route: "/admin/eventos",
        pageFile: "src/pages/admin/EventosPage.tsx",
        description: "CRUD de edições do JER (ano, datas, status). Permite criar, editar e ativar eventos. Seletor global de evento ativo.",
        roles: ["admin", "secretaria", "coordenacao_tecnica", "coordenador_modalidade"],
        status: ModuleStatus.DONE,
        dataSources: ["events"],
        gaps: [],
        nextActions: [],
      },
      {
        id: "instituicoes",
        label: "Instituições",
        route: "/admin/instituicoes",
        pageFile: "src/pages/admin/InstituicoesPage.tsx",
        description: "Cadastro de escolas/instituições (nome, cidade, rede, contato). Base para criação de delegações.",
        roles: ["admin", "secretaria", "coordenacao_tecnica", "coordenador_modalidade"],
        status: ModuleStatus.DONE,
        dataSources: ["institutions"],
        gaps: [],
        nextActions: [],
      },
      {
        id: "delegacoes",
        label: "Delegações",
        route: "/admin/delegacoes",
        pageFile: "src/pages/admin/DelegacoesPage.tsx",
        description: "Gerencia delegações vinculadas ao evento ativo. Cada delegação representa uma instituição participante com chefe e status.",
        roles: ["admin", "secretaria", "coordenacao_tecnica", "coordenador_modalidade"],
        status: ModuleStatus.DONE,
        dataSources: ["delegations", "institutions", "participants"],
        gaps: [],
        nextActions: [],
      },
      {
        id: "importacao",
        label: "Importação (SIGECOM)",
        route: "/admin/importacao",
        pageFile: "src/pages/admin/ImportacaoPage.tsx",
        description: "Upload de planilha XLSX com inscrições. Cria automaticamente people, participants, sport_events e participant_sport_events. Validação robusta com aliases de colunas.",
        roles: ["admin", "secretaria"],
        status: ModuleStatus.DONE,
        dataSources: ["import_logs", "import_row_errors", "people", "participants", "sport_events", "participant_sport_events", "institutions", "delegations"],
        gaps: ["Melhorar feedback de progresso em lote"],
        nextActions: ["Adicionar preview pré-importação"],
      },
      {
        id: "importacao-modelo",
        label: "Modelo padrão de importação",
        route: "/admin/importacao/modelo",
        pageFile: "src/pages/admin/ImportacaoModeloPage.tsx",
        description: "Gera dinamicamente o arquivo .xlsx modelo com cabeçalhos, dropdowns e instruções otimizados para minimizar erros de preenchimento.",
        roles: ["admin", "secretaria"],
        status: ModuleStatus.DONE,
        dataSources: ["sports", "categories", "sport_events", "delegations"],
        gaps: [],
        nextActions: [],
      },
      {
        id: "participantes",
        label: "Participantes",
        route: "/admin/participantes",
        pageFile: "src/pages/admin/ParticipantesPage.tsx",
        description: "Lista todos os participantes do evento ativo com filtros por delegação, tipo e status. Acesso a detalhes e histórico esportivo.",
        roles: ["admin", "secretaria", "coordenacao_tecnica", "coordenador_modalidade"],
        status: ModuleStatus.DONE,
        dataSources: ["participants", "people", "delegations"],
        gaps: [],
        nextActions: [],
      },
      {
        id: "pessoas",
        label: "Pessoas (cadastro central)",
        route: "/admin/pessoas",
        pageFile: "src/pages/admin/PessoasPage.tsx",
        description: "Cadastro central de pessoas (people) sem vínculo a evento. Permite criar/editar dados pessoais reaproveitáveis em múltiplos eventos e funções.",
        roles: ["admin", "secretaria"],
        status: ModuleStatus.DONE,
        dataSources: ["people", "participants"],
        gaps: [],
        nextActions: [],
      },
      {
        id: "pessoas-duplicidades",
        label: "Pessoas — Duplicidades",
        route: "/admin/pessoas/duplicidades",
        pageFile: "src/pages/admin/DuplicidadesPessoasPage.tsx",
        description: "Detecta e mescla pessoas duplicadas (mesmo CPF ou nome+nascimento), preservando histórico de participações e vouchers.",
        roles: ["admin", "secretaria"],
        status: ModuleStatus.DONE,
        dataSources: ["people", "participants", "service_vouchers"],
        gaps: [],
        nextActions: [],
      },
      {
        id: "vouchers",
        label: "Vouchers (QR de serviço)",
        route: "/admin/vouchers",
        pageFile: "src/pages/admin/VouchersPage.tsx",
        description: "Emissão, revogação e auditoria de vouchers QR de serviço (transporte, alimentação, alojamento). Geração de QR imprimível, histórico de uso e filtros por escopo/status.",
        roles: ["admin", "secretaria"],
        status: ModuleStatus.DONE,
        dataSources: ["service_vouchers", "service_voucher_uses", "participants", "people"],
        gaps: [],
        nextActions: [],
      },
      {
        id: "logistica-consolidada",
        label: "Logística Consolidada",
        route: "/admin/logistica/consolidada",
        pageFile: "src/pages/admin/LogisticaConsolidadaPage.tsx",
        description: "Painel agregado por pessoa: necessidades vs consumo de transporte, alimentação, alojamento e vouchers. KPIs, filtros por delegação/escopo/status e drill-down por pessoa com export CSV.",
        roles: ["admin", "secretaria", "coordenacao_tecnica", "transporte", "alimentacao", "alojamento"],
        status: ModuleStatus.DONE,
        dataSources: ["vw_person_logistics_consumption", "service_vouchers", "service_voucher_uses"],
        gaps: [],
        nextActions: [],
      },
    ],
  },
  {
    id: "credenciamento",
    label: "Credenciamento",
    items: [
      {
        id: "credenciamento",
        label: "Credenciamento",
        route: "/admin/credenciamento",
        pageFile: "src/pages/admin/CredenciamentoPage.tsx",
        description: "Busca participante por nome/CPF, ativa credencial, imprime etiqueta com QR. Bloqueia credenciamento se houver irregularidades pendentes.",
        roles: ["admin", "secretaria", "coordenacao_tecnica", "coordenador_modalidade"],
        status: ModuleStatus.DONE,
        dataSources: ["participant_credentials", "participants", "people", "participation_irregularities"],
        gaps: [],
        nextActions: [],
      },
      {
        id: "credenciamento-seguro",
        label: "Credenciamento (Seguro)",
        route: "/admin/credenciamento/seguro",
        pageFile: "src/pages/admin/CredenciamentoSeguroPage.tsx",
        description: "Fluxo guiado e validador: pre-flight de RPC/log, checagem de documentação aprovada e irregularidades antes de emitir. Mensagens de erro acionáveis para diagnóstico.",
        roles: ["admin", "secretaria", "coordenacao_tecnica"],
        status: ModuleStatus.DONE,
        dataSources: ["participant_credentials", "participants", "participant_documents", "participation_irregularities"],
        gaps: [],
        nextActions: [],
      },
      {
        id: "credenciais-modelos",
        label: "Modelos de Credencial",
        route: "/admin/credenciais/modelos",
        pageFile: "src/pages/admin/CredencialModelosPage.tsx",
        description: "CRUD de templates visuais para credenciais (dimensões, campos, background). Configuração de layout de impressão.",
        roles: ["admin", "secretaria", "coordenacao_tecnica", "coordenador_modalidade"],
        status: ModuleStatus.PARTIAL,
        dataSources: ["credential_templates"],
        gaps: ["Preview visual do template precisa de melhorias", "Falta upload de imagem de fundo"],
        nextActions: ["Melhorar editor visual de campos"],
      },
      {
        id: "validacao-qr",
        label: "Validação QR",
        route: "/admin/validacao-qr",
        pageFile: "src/pages/admin/ValidacaoQRPage.tsx",
        description: "Leitura de QR code da credencial para validar acesso em pontos de controle (alimentação, transporte, alojamento). Registra scan.",
        roles: ["admin", "secretaria", "coordenacao_tecnica", "transporte", "alimentacao"],
        status: ModuleStatus.DONE,
        dataSources: ["credential_scans", "participant_credentials", "participants", "people"],
        gaps: [],
        nextActions: [],
      },
      {
        id: "vinculacao-credencial",
        label: "Vinculação de Credencial",
        route: "/admin/credenciamento-externo",
        pageFile: "src/pages/admin/CredenciamentoExternoPage.tsx",
        description: "Vinculação de credenciais físicas (QR pré-impresso ou externo) aos participantes do evento.",
        roles: ["admin", "secretaria", "coordenacao_tecnica"],
        status: ModuleStatus.DONE,
        dataSources: ["external_credentials", "participants"],
        gaps: [],
        nextActions: [],
      },
    ],
  },
  {
    id: "competicao",
    label: "Competição",
    items: [
      {
        id: "painel-competicao",
        label: "Painel de Controle da Competição",
        route: "/admin/competicao/painel",
        pageFile: "src/pages/admin/CompeticaoPainelPage.tsx",
        description: "Visão consolidada do progresso de todas as provas do evento: status, etapas concluídas e acesso direto ao wizard.",
        roles: ["admin", "secretaria", "coordenacao_tecnica", "coordenador_modalidade"],
        status: ModuleStatus.DONE,
        dataSources: ["sport_events", "competition_phases", "competition_groups", "competition_matches", "competition_match_results", "teams", "participant_sport_events", "sport_event_rules"],
        gaps: [],
        nextActions: [],
      },
      {
        id: "pre-validacao",
        label: "Pré-validação de Provas",
        route: "/admin/competicao/pre-validacao",
        pageFile: "src/pages/admin/PreValidacaoPage.tsx",
        description: "Valida quórum de participantes/equipes por prova e libera provas aptas para a Central da Competição.",
        roles: ["admin", "secretaria", "coordenacao_tecnica", "coordenador_modalidade"],
        status: ModuleStatus.DONE,
        dataSources: ["sport_events", "participant_sport_events", "teams", "team_members", "sport_event_rules"],
        gaps: [],
        nextActions: [],
      },
      {
        id: "central-competicao",
        label: "Central da Competição",
        route: "/admin/competicao/central",
        pageFile: "src/pages/admin/CompeticaoCentralPage.tsx",
        description: "Painel único para gerenciar toda a competição: seleção de prova, estrutura (fases/grupos), geração de partidas, lançamento de resultados e pendências de elegibilidade.",
        roles: ["admin", "secretaria", "coordenacao_tecnica", "coordenador_modalidade"],
        status: ModuleStatus.DONE,
        dataSources: ["competition_matches", "competition_match_entries", "competition_phases", "competition_groups", "teams", "participant_sport_events", "competition_match_results"],
        gaps: [],
        nextActions: [],
      },
      {
        id: "regras-evento",
        label: "Regras do Evento",
        route: "/admin/regras",
        pageFile: "src/pages/admin/RegrasEventoPage.tsx",
        description: "Painel centralizado das regras gerais da edição: identificação, categorias, modalidades, limites, classificação, regras operacionais, pontuação e publicação/versionamento.",
        roles: ["admin", "secretaria", "coordenacao_tecnica"],
        status: ModuleStatus.PARTIAL,
        dataSources: ["event_edition_rules", "event_rules_audit_log", "events", "categories", "sports"],
        gaps: ["Ainda depende de consolidação com regras por prova e documentação operacional"],
        nextActions: ["Ampliar cobertura das regras e cruzamentos com módulos consumidores"],
      },
      {
        id: "modalidades",
        label: "Modalidades",
        route: "/admin/modalidades",
        pageFile: "src/pages/admin/ModalidadesPage.tsx",
        description: "CRUD de modalidades esportivas do evento (futebol, atletismo etc). Define tipo (coletivo/individual) e provas vinculadas (sport_events).",
        roles: ["admin", "secretaria", "coordenacao_tecnica", "coordenador_modalidade"],
        status: ModuleStatus.DONE,
        dataSources: ["sports", "sport_events"],
        gaps: [],
        nextActions: [],
      },
      {
        id: "categorias",
        label: "Categorias",
        route: "/admin/categorias",
        pageFile: "src/pages/admin/CategoriasPage.tsx",
        description: "CRUD de categorias por faixa etária e gênero (ex: 12-14 masc). Vinculadas ao evento ativo.",
        roles: ["admin", "secretaria", "coordenacao_tecnica", "coordenador_modalidade"],
        status: ModuleStatus.DONE,
        dataSources: ["categories"],
        gaps: [],
        nextActions: [],
      },
      {
        id: "fases",
        label: "Fases",
        route: "/admin/competicao/fases",
        pageFile: "src/pages/admin/CompeticaoFasesPage.tsx",
        description: "Gerencia fases de competição (classificatória, eliminatória, final) por modalidade/prova.",
        roles: ["admin", "secretaria", "coordenacao_tecnica", "coordenador_modalidade"],
        status: ModuleStatus.PARTIAL,
        dataSources: ["competition_phases", "sport_events"],
        gaps: ["Falta transição automática de status entre fases"],
        nextActions: ["Implementar progressão automática"],
      },
      {
        id: "grupos",
        label: "Grupos",
        route: "/admin/competicao/grupos",
        pageFile: "src/pages/admin/CompeticaoGruposPage.tsx",
        description: "Gerencia grupos dentro de cada fase (Grupo A, B etc). Usado para chaveamento.",
        roles: ["admin", "secretaria", "coordenacao_tecnica", "coordenador_modalidade"],
        status: ModuleStatus.PARTIAL,
        dataSources: ["competition_groups", "competition_phases"],
        gaps: ["Falta sorteio automático de equipes nos grupos"],
        nextActions: ["Adicionar sorteio/distribuição automática"],
      },
      {
        id: "equipes",
        label: "Equipes",
        route: "/admin/competicao/equipes",
        pageFile: "src/pages/admin/CompeticaoEquipesPage.tsx",
        description: "Gerencia equipes (times) por modalidade coletiva. Vincula participantes como membros com número de camisa.",
        roles: ["admin", "secretaria", "coordenacao_tecnica", "coordenador_modalidade"],
        status: ModuleStatus.PARTIAL,
        dataSources: ["teams", "team_members", "participants"],
        gaps: ["Validação de elegibilidade na composição do time"],
        nextActions: ["Integrar verificação de irregularidades ao montar equipe"],
      },
      {
        id: "partidas",
        label: "Partidas e Agenda",
        route: "/admin/competicao/partidas-agenda",
        pageFile: "src/pages/admin/CompeticaoPartidasAgendaPage.tsx",
        description: "Lista, gerencia e agenda partidas/confrontos com visão de lista e calendário. Consolida as antigas páginas de Partidas e Agenda.",
        roles: ["admin", "secretaria", "coordenacao_tecnica", "coordenador_modalidade"],
        status: ModuleStatus.DONE,
        dataSources: ["competition_matches", "competition_match_entries", "venues"],
        gaps: [],
        nextActions: [],
      },
      {
        id: "resultados",
        label: "Resultados",
        route: "/admin/competicao/resultados",
        pageFile: "src/pages/admin/CompeticaoResultadosPage.tsx",
        description: "Registra e publica resultados de partidas. Suporta placar coletivo e ranking individual (tempo, distância, pontos).",
        roles: ["admin", "secretaria", "coordenacao_tecnica", "coordenador_modalidade"],
        status: ModuleStatus.PARTIAL,
        dataSources: ["competition_match_results", "competition_match_entries", "match_scores"],
        gaps: ["Publicação em lote", "Ranking geral por modalidade"],
        nextActions: ["Implementar quadro de medalhas"],
      },
      {
        id: "arbitragem",
        label: "Arbitragem",
        route: "/admin/competicao/arbitragem",
        pageFile: "src/pages/admin/ArbitragemEquipePage.tsx",
        description: "Escalas por etapa e modalidade usando os usuários cadastrados para liberar partidas no JER Ao Vivo.",
        roles: ["admin", "secretaria", "coordenacao_tecnica", "coordenador_modalidade", "arbitragem"],
        status: ModuleStatus.DONE,
        dataSources: ["match_user_assignments", "competition_matches", "profiles"],
        gaps: [],
        nextActions: [],
      },
      {
        id: "painel-score",
        label: "Painel de Confrontos (Score)",
        route: "/admin/competicao/painel-score",
        pageFile: "src/pages/admin/CompeticaoPainelScorePage.tsx",
        description: "Gestão operacional de confrontos e resultados para modalidades de placar (futebol, futsal, basquete etc).",
        roles: ["admin", "secretaria", "coordenacao_tecnica", "coordenador_modalidade"],
        status: ModuleStatus.DONE,
        dataSources: ["competition_matches", "competition_match_results", "match_scores"],
        gaps: [],
        nextActions: [],
      },
      {
        id: "painel-sets",
        label: "Painel de Confrontos (Sets)",
        route: "/admin/competicao/painel-sets",
        pageFile: "src/pages/admin/CompeticaoPainelSetsPage.tsx",
        description: "Gestão operacional de confrontos e resultados para modalidades de sets e parciais (vôlei, tênis de mesa etc).",
        roles: ["admin", "secretaria", "coordenacao_tecnica", "coordenador_modalidade"],
        status: ModuleStatus.DONE,
        dataSources: ["competition_matches", "competition_match_results", "match_scores"],
        gaps: [],
        nextActions: [],
      },
    ],
  },
  {
    id: "logistica",
    label: "Logística",
    items: [],
    subGroups: [
      {
        label: "Transporte",
        items: [
          {
            id: "veiculos",
            label: "Veículos",
            route: "/admin/transporte/veiculos",
            pageFile: "src/pages/admin/TransporteVeiculosPage.tsx",
            description: "Cadastro de veículos disponíveis (ônibus, vans) com capacidade, placa e motorista.",
            roles: ["admin", "secretaria", "coordenacao_tecnica", "transporte"],
            status: ModuleStatus.PARTIAL,
            dataSources: ["transport_vehicles"],
            gaps: ["Falta controle de manutenção/disponibilidade"],
            nextActions: ["Adicionar status do veículo"],
          },
          {
            id: "rotas",
            label: "Rotas",
            route: "/admin/transporte/rotas",
            pageFile: "src/pages/admin/TransporteRotasPage.tsx",
            description: "Define rotas de transporte (origem, destino, pontos de parada).",
            roles: ["admin", "secretaria", "coordenacao_tecnica", "transporte"],
            status: ModuleStatus.PARTIAL,
            dataSources: ["transport_routes"],
            gaps: ["Falta mapa visual de rotas"],
            nextActions: [],
          },
          {
            id: "viagens",
            label: "Viagens",
            route: "/admin/transporte/viagens",
            pageFile: "src/pages/admin/TransporteViagensPage.tsx",
            description: "Agenda viagens vinculando rota, veículo, data/hora e passageiros. Controle de embarque.",
            roles: ["admin", "secretaria", "coordenacao_tecnica", "transporte"],
            status: ModuleStatus.PARTIAL,
            dataSources: ["transport_trips", "transport_passengers", "transport_vehicles", "transport_routes"],
            gaps: ["Lotação em tempo real", "Confirmação de embarque por QR"],
            nextActions: ["Integrar scan QR ao embarque"],
          },
        ],
      },
      {
        label: "Alimentação",
        items: [
          {
            id: "alimentacao-tipos",
            label: "Refeições",
            route: "/admin/alimentacao/tipos",
            pageFile: "src/pages/admin/AlimentacaoTiposPage.tsx",
            description: "Cadastro de tipos de refeição (café, almoço, jantar, lanche).",
            roles: ["admin", "secretaria", "coordenacao_tecnica", "alimentacao"],
            status: ModuleStatus.DONE,
            dataSources: ["meal_types"],
            gaps: [],
            nextActions: [],
          },
          {
            id: "alimentacao-janelas",
            label: "Janelas",
            route: "/admin/alimentacao/janelas",
            pageFile: "src/pages/admin/AlimentacaoJanelasPage.tsx",
            description: "Define janelas de serviço (horário início/fim, local) para cada tipo de refeição por dia.",
            roles: ["admin", "secretaria", "coordenacao_tecnica", "alimentacao"],
            status: ModuleStatus.DONE,
            dataSources: ["meal_windows", "meal_types"],
            gaps: [],
            nextActions: [],
          },
          {
            id: "alimentacao-consumo",
            label: "Consumo",
            route: "/admin/alimentacao/consumo",
            pageFile: "src/pages/admin/AlimentacaoConsumoPage.tsx",
            description: "Registro de consumo de refeições por participante (via scan QR ou manual). Relatórios de consumo.",
            roles: ["admin", "secretaria", "coordenacao_tecnica", "alimentacao"],
            status: ModuleStatus.PARTIAL,
            dataSources: ["meal_consumptions", "meal_windows", "participants"],
            gaps: ["Falta dashboard de consumo em tempo real", "Relatório exportável"],
            nextActions: ["Dashboard com contadores ao vivo"],
          },
        ],
      },
      {
        label: "Alojamento",
        items: [
          {
            id: "alojamento-locais",
            label: "Locais de Alojamento",
            route: "/admin/alojamento/locais",
            pageFile: "src/pages/admin/AlojamentoLocaisPage.tsx",
            description: "Cadastro de locais de alojamento (escolas, ginásios, hotéis) com endereço e notas.",
            roles: ["admin", "secretaria", "coordenacao_tecnica", "coordenador_modalidade"],
            status: ModuleStatus.DONE,
            dataSources: ["lodging_locations"],
            gaps: [],
            nextActions: [],
          },
          {
            id: "alojamento-unidades",
            label: "Unidades do Alojamento",
            route: "/admin/alojamento/unidades",
            pageFile: "src/pages/admin/AlojamentoUnidadesPage.tsx",
            description: "Cadastro de unidades (quartos/salas) por local, com capacidade e restrição de gênero.",
            roles: ["admin", "secretaria", "coordenacao_tecnica", "coordenador_modalidade"],
            status: ModuleStatus.DONE,
            dataSources: ["lodging_units", "lodging_locations"],
            gaps: [],
            nextActions: [],
          },
          {
            id: "alojamento-ocupacao",
            label: "Ocupação",
            route: "/admin/alojamento/ocupacao",
            pageFile: "src/pages/admin/AlojamentoOcupacaoPage.tsx",
            description: "Alocação de participantes em unidades. Check-in/check-out com controle de lotação.",
            roles: ["admin", "secretaria", "coordenacao_tecnica", "coordenador_modalidade"],
            status: ModuleStatus.PARTIAL,
            dataSources: ["lodging_occupancies", "lodging_units", "participants"],
            gaps: ["Falta visualização de mapa de ocupação", "Relatório de vagas"],
            nextActions: ["Dashboard visual de ocupação"],
          },
        ],
      },
    ],
  },
  {
    id: "cadastros",
    label: "Cadastros",
    items: [
      {
        id: "locais",
        label: "Locais de Competição",
        route: "/admin/locais",
        pageFile: "src/pages/admin/LocaisPage.tsx",
        description: "Cadastro de locais onde acontecem as competições (ginásios, quadras, pistas).",
        roles: ["admin", "secretaria", "coordenacao_tecnica", "coordenador_modalidade"],
        status: ModuleStatus.DONE,
        dataSources: ["venues"],
        gaps: [],
        nextActions: [],
      },
    ],
  },
  {
    id: "acessos",
    label: "Acessos",
    items: [
      {
        id: "acessos-delegacoes",
        label: "Vínculos Delegação",
        route: "/admin/acessos/delegacoes",
        pageFile: "src/pages/admin/AcessosDelegacoesPage.tsx",
        description: "Vincula usuários do sistema a delegações específicas, permitindo acesso restrito por delegação.",
        roles: ["admin", "secretaria"],
        status: ModuleStatus.PARTIAL,
        dataSources: ["user_roles", "delegations", "profiles"],
        gaps: ["Falta convite por e-mail", "Falta log de alterações de vínculo"],
        nextActions: ["Implementar fluxo de convite"],
      },
    ],
  },
  {
    id: "configuracoes",
    label: "Configurações",
    items: [
      {
        id: "regras-evento",
        label: "Regras do Evento",
        route: "/admin/regras",
        pageFile: "src/pages/admin/RegrasEventoPage.tsx",
        description: "Painel centralizado com todas as regras do evento incluindo limites de participação, edição, categorias, modalidades, classificação, operacionais, pontuação e publicação com versionamento e auditoria.",
        roles: ["admin", "secretaria", "coordenacao_tecnica"],
        status: ModuleStatus.DONE,
        dataSources: ["event_edition_rules", "event_rules_audit_log", "event_participation_rules"],
        gaps: [],
        nextActions: [],
      },
      {
        id: "irregularidades",
        label: "Irregularidades",
        route: "/admin/irregularidades",
        pageFile: "src/pages/admin/IrregularidadesPage.tsx",
        description: "Lista irregularidades detectadas (excesso de inscrições, idade fora da faixa etc). Permite resolver ou ignorar.",
        roles: ["admin", "secretaria", "coordenacao_tecnica", "coordenador_modalidade"],
        status: ModuleStatus.DONE,
        dataSources: ["participation_irregularities", "participants", "people"],
        gaps: [],
        nextActions: [],
      },
      {
        id: "normalizacao-provas",
        label: "Normalização de Provas",
        route: "/admin/normalizacao-provas",
        pageFile: "src/pages/admin/NormalizacaoProvasPage.tsx",
        description: "Mapeia nomes de provas importados (variações) para sport_events canônicos do sistema. Evita duplicidade.",
        roles: ["admin", "secretaria", "coordenacao_tecnica", "coordenador_modalidade"],
        status: ModuleStatus.DONE,
        dataSources: ["sport_events", "participant_sport_events"],
        gaps: [],
        nextActions: [],
      },
      {
        id: "schema-validador",
        label: "Validador de Estrutura",
        route: "/admin/schema/validador",
        pageFile: "src/pages/admin/SchemaValidadorPage.tsx",
        description: "Compara estrutura de planilha XLSX com o schema do Supabase. Identifica tabelas e colunas faltantes ou extras.",
        roles: ["admin", "secretaria"],
        status: ModuleStatus.DONE,
        dataSources: [],
        gaps: [],
        nextActions: [],
      },
      {
        id: "mapa-sistema",
        label: "Mapa do Sistema",
        route: "/admin/sistema/diagnostico",
        pageFile: "src/pages/admin/MapaSistemaPage.tsx",
        description: "Visão geral de todos os módulos do sistema com status de implementação, gaps e próximos passos.",
        roles: ["admin", "secretaria", "coordenacao_tecnica", "coordenador_modalidade"],
        status: ModuleStatus.DONE,
        dataSources: [],
        gaps: [],
        nextActions: [],
      },
      {
        id: "diagnostico-competicao",
        label: "Diagnóstico (Competição)",
        route: "/admin/diagnostico-competicao",
        pageFile: "src/pages/admin/DiagnosticoCompeticaoPage.tsx",
        description: "Visão auditável de rotas, entidades, tabelas Supabase e KPIs da competição. Exporta JSON completo.",
        roles: ["admin", "coordenacao_tecnica"],
        status: ModuleStatus.DONE,
        dataSources: ["competition_matches", "competition_match_results", "sport_events", "participant_sport_events"],
        gaps: [],
        nextActions: [],
      },
      {
        id: "sistema-diagnostico",
        label: "Diagnóstico do Sistema",
        route: "/admin/sistema/diagnostico",
        pageFile: "src/pages/admin/SistemaDiagnosticoPage.tsx",
        description: "Aglutinador com Mapa do Sistema e Diagnóstico da Competição em abas.",
        roles: ["admin", "coordenacao_tecnica"],
        status: ModuleStatus.DONE,
        dataSources: [],
        gaps: [],
        nextActions: [],
      },
      {
        id: "seed-logistica",
        label: "Seed Logística",
        route: "/admin/seed-logistica",
        pageFile: "src/pages/admin/SeedLogisticaPage.tsx",
        description: "Geração e limpeza de dados demo de logística (alojamento, alimentação, transporte) por etapa.",
        roles: ["admin", "secretaria"],
        status: ModuleStatus.DONE,
        dataSources: [],
        gaps: [],
        nextActions: [],
      },
    ],
  },
  {
    id: "ajuda",
    label: "Ajuda",
    items: [
      {
        id: "ajuda",
        label: "Central de Ajuda",
        route: "/admin/ajuda",
        pageFile: "src/pages/admin/AjudaManualPage.tsx",
        description: "Manual oficial de uso e chat com IA de suporte (responde com base no manual).",
        roles: ["admin", "secretaria", "coordenacao_tecnica", "coordenador_modalidade"],
        status: ModuleStatus.DONE,
        dataSources: ["help_manual_sections"],
        gaps: [],
        nextActions: [],
      },
    ],
  },
];

// Helper: flatten all items
export function getAllItems(): (SystemMapItem & { groupLabel: string })[] {
  const result: (SystemMapItem & { groupLabel: string })[] = [];
  for (const group of systemMap) {
    for (const item of group.items) {
      result.push({ ...item, groupLabel: group.label });
    }
    if (group.subGroups) {
      for (const sg of group.subGroups) {
        for (const item of sg.items) {
          result.push({ ...item, groupLabel: `${group.label} › ${sg.label}` });
        }
      }
    }
  }
  return result;
}

// Helper: summary counts
export function getStatusSummary() {
  const items = getAllItems();
  return {
    total: items.length,
    done: items.filter((i) => i.status === ModuleStatus.DONE).length,
    partial: items.filter((i) => i.status === ModuleStatus.PARTIAL).length,
    notStarted: items.filter((i) => i.status === ModuleStatus.NOT_STARTED).length,
  };
}
