// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { createSupabaseFetchInterceptor } from '@/lib/monitoring/supabaseInstrumentation';

// Defaults (fallback do projeto Lovable original)
const DEFAULT_SUPABASE_URL = "https://dfzjrijdcskncrwaiykr.supabase.co";
const DEFAULT_SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRmempyaWpkY3NrbmNyd2FpeWtyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUxNTUwNjYsImV4cCI6MjA5MDczMTA2Nn0.jYPuKoPcNC5sEBLXtgTyo9e4oqDsc69zOVrzHrf4lUw";

// Override runtime salvo via /admin/configuracoes/supabase
// Prioridade: localStorage override > VITE_* env > fallback hardcoded
const LS_URL_KEY = "jer_supabase_url_override";
const LS_KEY_KEY = "jer_supabase_anon_key_override";

function readLocalStorage(key: string): string | null {
  try {
    if (typeof window === "undefined" || !window.localStorage) return null;
    const v = window.localStorage.getItem(key);
    return v && v.trim() ? v.trim() : null;
  } catch {
    return null;
  }
}

const SUPABASE_URL =
  readLocalStorage(LS_URL_KEY) ||
  import.meta.env.VITE_SUPABASE_URL ||
  DEFAULT_SUPABASE_URL;

const SUPABASE_PUBLISHABLE_KEY =
  readLocalStorage(LS_KEY_KEY) ||
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
  DEFAULT_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    fetch: createSupabaseFetchInterceptor(window.fetch.bind(window))
  }
});

// For telemetry to avoid any recursion risk
export const rawSupabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Helpers expostos para a tela de configuração
export const SUPABASE_OVERRIDE_KEYS = { url: LS_URL_KEY, anonKey: LS_KEY_KEY } as const;
export const SUPABASE_DEFAULTS = {
  url: DEFAULT_SUPABASE_URL,
  anonKey: DEFAULT_SUPABASE_PUBLISHABLE_KEY,
} as const;
export const ACTIVE_SUPABASE = { url: SUPABASE_URL, anonKey: SUPABASE_PUBLISHABLE_KEY } as const;
